/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.kkrull.java-sandbox;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
