name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Java Setup
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Java Configuration
      run: |
        java -version

    - name: Gradle Build and Test
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: test

    - name: Gradle Configuration
      run: |
        ./gradlew --version
