name: Publish Java Library

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    env:
      working-directory: greeter

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Java setup
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Java configuration
      run: |
        java -version
      working-directory: ${{env.working-directory}}

    - name: Gradle validation
      uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b

    - name: Gradle build
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: test
        build-root-directory: ${{env.working-directory}}
